### ISSUE TITLE
add gometalinter.json?

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/project#10]
Can we add gometalinter.json to this repo so that we can catch lint/fmt issues like https://github.com/containerd/cgroups/pull/62 ?

cc @estesp

**Comment by AkihiroSuda** [comment]
Although we need a `containerd`-specific line in the JSON: https://github.com/containerd/containerd/blob/52893fbb05a32d3f6c14c65ce47e73aaf6f71705/.gometalinter.json#L7

**Comment by estesp** [comment]
I have done a little testing moving the config and script into common project repo; we may have to do PRs across any projects we want to use it for to fix initial issues; e.g. for `containerd/console`:
```
console.go:25:5:warning: exported var ErrNotAConsole should have comment or be unexported (golint)
console.go:27:6:warning: exported type Console should have comment or be unexported (golint)
console.go:73:6:warning: func name will be used as console.ConsoleFromFile by other packages, and that stutters; consider calling this FromFile (golint)
```
