### ISSUE TITLE
[governance] discuss Moby TSC umbrella vs. in-project governance only

### ISSUE THREAD

**Issue by estesp** [containerd/project#15]
Per the CNCF TOC graduation [vote discussion](https://github.com/cncf/toc/pull/165#issuecomment-465257994), this issue reflects our commitment to revisit project governance with external connection to the Moby TSC.

**Comment by stevvooe** [comment]
Ay!

Current language is here:

> containerd defers to the Moby Technical Steering Committee for escalations and resolution on disputes for technical matters.

**Comment by crosbymichael** [comment]
I'm in favor of removing the TSC and having decisions left to the maintainers of containerd.  The project is mature enough and we have a large, diverse group of maintainers on the project to handle these issues.  

ping @containerd/containerd-maintainers @containerd/containerd-reviewers

**Comment by jhowardmsft** [comment]
+1 to what @crosbymichael said

**Comment by mlaventure** [comment]
Sounds good to me, Containerd has grown enough that active maintainers should be able to take on that responsibilities.

**Comment by fuweid** [comment]
+1 SGTM

**Comment by Ace-Tang** [comment]
Really a good news :+1:

**Comment by AkihiroSuda** [comment]
SGTM

**Comment by estesp** [comment]
Just to be clear, I'm in favor of this as well.

**Comment by jterry75** [comment]
+1 SGTM

**Comment by hqhq** [comment]
SGTM

**Comment by ehazlett** [comment]
SGTM

**Comment by dqminh** [comment]
SGTM

**Comment by mikebrow** [comment]
> I'm in favor of removing the TSC and having decisions left to the maintainers of containerd. The project is mature enough and we have a large, diverse group of maintainers on the project to handle these issues.

+1 SGTM

**Comment by yanxuean** [comment]
> removing the TSC
+1 SGTM

**Comment by Random-Liu** [comment]
> removing the TSC

+1

**Comment by yujuhong** [comment]
+1

**Comment by miaoyq** [comment]
+1

**Comment by dchen1107** [comment]
+1 on what @crosbymichael said.

**Comment by dmcgowan** [comment]
+1
I am glad to see this is unanimous. I think it reflects nicely on the maturity of the project and this group as a whole.

**Comment by crosbymichael** [comment]
I opened #16 to resolve this since everyone is in favor of the change.
