### ISSUE TITLE
Adding ttrpc-rust as sub-project

### ISSUE THREAD

**Issue by teawater** [containerd/project#33]
We just open source our ttrpc-rust implementation in https://github.com/alipay/ttrpc-rust and https://crates.io/crates/ttrpc .
We would like add it as sub-project of containerd.

Please help us about the process.  Thanks!

**Comment by crosbymichael** [comment]
What are you thoughts on who will maintain this project after the move?

**Comment by teawater** [comment]
> What are you thoughts on who will maintain this project after the move?

@gnawux Do you have any idea on this?

**Comment by teawater** [comment]
> What are you thoughts on who will maintain this project after the move?

@crosbymichael We (kata team in antfin) will keep maintain this project.  But we are open to donations.
Do you have any opinions?

**Comment by crosbymichael** [comment]
What works.  Do we want this as a separate repo or part of the TTRPC repo?

**Comment by estesp** [comment]
Given our governance, it would make sense to have it be its own non-core repo so that it can have its own maintainers who don't need to worry about the rest of the org. core repos.

Also, seems like a project using a different programming language would just be cleaner as its own repo with its own CI, Makefile, scripts, etc. which I assume will not be aligned with the rest of the Golang-focused repos. It can also be tagged and released on its own timeline as well as a separate repo.

**Comment by teawater** [comment]
@crosbymichael I think comments from @estesp is what I think about.
What do you think about let ttrpc-rust as a separate repo?

**Comment by crosbymichael** [comment]
@teawater that works for me.  Sounds good!

**Comment by estesp** [comment]
@crosbymichael should we open a separate issue with a formal proposal for a vote? I think other than what we already know about the project, we would want a list of potential maintainers (so far @teawater is the only contributor to the existing project I think?) and agreement to add the boilerplate re: CNCF code of conduct and containerd governance.

**Comment by crosbymichael** [comment]
Ya, i was thinking all we need now is a formal proposal with the list of maintainers and the repo up to spec with the boilerplate

**Comment by teawater** [comment]
Thanks @estesp @crosbymichael 

Are there any previous proposals could be used as references? 

PS: @lifupan may be a second maintainer for the project.

**Comment by crosbymichael** [comment]
You can look at https://github.com/containerd/project/issues/37

**Comment by AkihiroSuda** [comment]
@teawater Do you want to call for votes?

**Comment by teawater** [comment]
@AkihiroSuda yes.

**Comment by AkihiroSuda** [comment]
@teawater could you open an issue for voting as in #37 ?

**Comment by teawater** [comment]
I have raised the proposal/voting in #40 and I think this issue could be closed.

Thanks @estesp @crosbymichael and @AkihiroSuda
