### ISSUE TITLE
Add non-core project "imgcrypt" to containerd organization

### ISSUE THREAD

**Issue by estesp** [containerd/project#37]
Over the past year there were many PRs and discussions about the encrypted container image support proposed across OCI, Kubernetes, and the runtimes including containerd. We finally agreed on the [stream processor implementation](https://github.com/containerd/containerd/pull/3482), available in the 1.3 release, to allow media types to have an external processor binary which can handle actions on that stream of bytes on behalf of containerd. This allows containerd's core to not include special case code or implementation details for this and any future special media types, modes of compression, and so on.

@stefanberger and @lumjjb have prepared the [stefanberger/imgcrypt](https://github.com/stefanberger/imgcrypt) repository for migration to the containerd organization. 

This is specifically proposed as a **non-core** project per the recent project modes we added to containerd's governance. The maintainers of the repository will be Stefan Berger and Brandon Lum.

For a broader view of this work across many projects and repositories, a recent comment by @lumjjb is extremely helpful to see the full scope and status of the work: https://github.com/opencontainers/image-spec/pull/775#issuecomment-540060318

Having this repository as part of the containerd organization is valuable as it allows users/operators to assemble and deliver the required stream processors which can handle the encrypted layer media types as part of the containerd project umbrella. This repository currently includes features for `ctr` which were not accepted in the containerd core, but are extremely helpful for those trying to handle the current "chicken and egg" issue of not having a tool to test the encryption and decryption of layers. As this work matures and these capabilities are available across tools like `buildkit` and various other container build pipelines, it will be less necessary to have a special `ctr` tool for testing.

9 maintainer's LGTM required (2/3)

- [x] @estesp (implied)
- [x] @mxpv
- [x] @AkihiroSuda
- [x] @crosbymichael
- [ ] @dmcgowan
- [x] @jterry75
- [x] @mlaventure
- [ ] @stevvooe
- [x] @dchen1107
- [x] @Random-Liu
- [x] @mikebrow
- [x] @yujuhong
- [x] @fuweid

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by mxpv** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM

**Comment by jterry75** [comment]
LGTM!

**Comment by fuweid** [comment]
LGTM

**Comment by Random-Liu** [comment]
LGTM

**Comment by mikebrow** [comment]
SGTM

**Comment by yujuhong** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM and thanks!

**Comment by estesp** [comment]
11/13 LGTMs (2 more than required)

@crosbymichael can you work with @stefanberger on the mechanics of the transfer? Thanks!

**Comment by crosbymichael** [comment]
@estesp @stefanberger yep

**Comment by crosbymichael** [comment]
done

https://github.com/containerd/imgcrypt

**Comment by lumjjb** [comment]
Thanks @crosbymichael ! 🍾
