### ISSUE TITLE
Add non-core project "remote-snapshotter" to containerd organization

### ISSUE THREAD

**Issue by ktock** [containerd/project#41]
Pull operation is one of the time-consuming steps in container's lifecycle. To address this issue, we've discussed "Remote Snapshotter" plugin (containerd/containerd#3731, containerd/containerd#2968 and containerd/containerd#2943, etc.). It allows containerd to prepare snapshots by directly mounting them from remote stores, which is much faster than downloading and unpacking entire image contents.

[ktock/remote-snapshotter](https://github.com/ktock/remote-snapshotter) is a Remote Snapshotter implementation based on the discussions. It's been used as a blueprint in containerd/containerd#3731 also used for testing some Remote Snapshotter related patches containerd/containerd#3911, containerd/containerd#3846 and containerd/containerd#3793). It supports standard-compatible remote snapshots with stargz image format by default and CermVM-FS is also under the integration work leveraging the remote-snapshotter's pluggable architecture. For more details about the functionality of remote-snapshotter, please see [our documentation](https://github.com/ktock/remote-snapshotter/blob/master/overview.md).

We still need further discussion inside/outside of containerd including client tools like CRI plugin and Buildkit for improving and leveraging Remote Snapshotter functionality. Adding remote-snapshotter to containerd project umbrella is valuable to encourage such cross-project discussions based on the official implementation and also to gather more collaborators for this movement.

Kohei Tokunaga(@ktock) have prepared the [ktock/remote-snapshotter](https://github.com/ktock/remote-snapshotter) repository for migration to the containerd organization. This is specifically proposed as a non-core project per the recent project modes we added to containerd's governance. Kohei Tokunaga(@ktock) will be an initial maintainer of the repository. According to the non-core document requirement, we will add the boilerplate to the project (ktock/remote-snapshotter#23).

9 maintainer's LGTM required (2/3)

* [ ]  @estesp
* [ ]  @mxpv
* [x]  @AkihiroSuda
* [ ]  @crosbymichael
* [ ]  @dmcgowan
* [ ]  @jterry75
* [ ]  @mlaventure
* [ ]  @stevvooe
* [ ]  @dchen1107
* [ ]  @Random-Liu
* [ ]  @mikebrow
* [ ]  @yujuhong
* [ ]  @fuweid

**Comment by AkihiroSuda** [comment]
LGTM 🎉

**Comment by fuweid** [comment]
Hi @ktock , Thanks for contributing for remote snapshotter. :)

But I still have two questions for this. Remote snapshotter can be proxy snapshotter. What is different between [ktock/remote-snapshotter](https://github.com/ktock/remote-snapshotter) and customized proxy snapshotter?

And IIUC, someone wants to contribute remote snapshotter into [fsplugins]( 
https://github.com/ktock/remote-snapshotter/tree/master/filesystems), is there any accept rule for this?

Thanks!

**Comment by AkihiroSuda** [comment]
ktock/remote-snapshotter  is implemented as as a proxy snapshotter and will remain as a proxy snapshotter for the foreseeable future.
This PR does not propose adding remote-snapshotter as a builtin plugin.

**Comment by ktock** [comment]
@fuweid Thanks for your question!

"remote-snapshotter" is implemented and proposed as a proxy plugin project as @AkihiroSuda mentioned. We don't have explicit rules to merge fsplugins but for openness and sustainability, I think it's good to have a policy "Multiple(2 or more) organizations contribute or use the image format/filesystem".

**Comment by dmcgowan** [comment]
I am fining pulling this in, but I think it needs to be scoped a little tighter and named accordingly. This is an implementation of an overlayfs snapshotter with remotely managed lower directories and currently backed by CRFS (with a plugin interface). There are many other ways we have discussed being able to do remote snapshotters, so we should avoid keeping the name so generic. I think it is best to focus on having a configurable snapshotter which can define a backend rather than having a single instance snapshotter with plug-able backends. That can be discussed as part of the project, but I think it is relevant here for scoping and naming the project in the containerd namespace.

**Comment by AkihiroSuda** [comment]
> I think it is best to focus on having a configurable snapshotter which can define a backend rather than having a single instance snapshotter with plug-able backends. 

This can be achieved by just registering multiple remote snapshotter instances with different IDs?

**Comment by ktock** [comment]
@dmcgowan I agree that there are many ways to have remote snapshots and that we should avoid generic name for this proposal. To tighten the scope of this proposal and avoid too generic name, how about the following plan?

- tightening the scope of the proposal by making the proposed remote-snapshotter non-pluggable about filesystems and by combining the remote-snapshotter and stargzfs into one component
- avoiding generic name by naming the proposed snapshotter as  "stargz-snapshotter"(not "remote-snapshotter")

Users can still use multiple remote snapshots by configuring containerd to use the snapshotter they want.

**Comment by fuweid** [comment]
Sorry for the late reply. @AkihiroSuda @ktock I am fine with this project. 

But I think there are the following-up remote snapshotters with different design and `remote-snapshotter` is too big for others. It will be great if using `stargz-snapshotter` as proposal, which is more accurate and acceptable name. :)

**Comment by mikebrow** [comment]
SGTM with proposed scope tightening
stargz-remote-snapshotter or
stargz-snapshotter

**Comment by ktock** [comment]
Thanks for feedback here(and on slack)! Based on the discussion, I'm working on fixing snapshotter design in ktock/remote-snapshotter#32 as following:

- Make the snapshotter configurable and generic parts(snapshotter, cache, ...) importable for other remote snapshotter developers and
- tighten the scope of the project to one filesystem(= CRFS/stargz).

I'll reopen another issue here when I'm done.

**Comment by ktock** [comment]
I've done the redesigning! And I've reopened the issue on #43.
Thanks @AkihiroSuda, @fuweid, @dmcgowan and @mikebrow  for all feedbacks!
