### ISSUE TITLE
Add non-core project "stargz-snapshotter" to containerd organization

### ISSUE THREAD

**Issue by ktock** [containerd/project#43]
Pull operation is one of the time-consuming steps in container's lifecycle. To address this issue, we've been discussing "Remote Snapshotter" plugin. Please refer to the previous proposal(#41) for the general context in containerd community.

"stargz-snapshotter"([ktock/stargz-snapshotter](https://github.com/ktock/stargz-snapshotter)) is a remote snapshotter implementation which has the following features:

- standard compatible remote snapshots leveraging [stargz format by CRFS](https://github.com/google/crfs), which we can use with standard-compliant registry
- [generic remote snapshotter package](https://github.com/ktock/stargz-snapshotter/blob/master/README.md#make-your-remote-snapshotter) which is importable as Go packages and configurable for other remote snapshotter developers(based on the previous discussion #41)

Adding stargz-snapshotter to containerd project umbrella as the first implementation of remote snapshotters is valuable to push the remote snapshotter's movement forward. Following-up remote snapshotters can use the generic(and official) parts to easily create their implementation with filesystems they like. There is an ongoing work of implementing remote snapshotter in CernVM-FS community(ktock/stargz-snapshotter#27), but we propose only stargz-based snapshotter here.

Kohei Tokunaga(@ktock) have prepared the [ktock/stargz-snapshotter](https://github.com/ktock/stargz-snapshotter) repository for migration to the containerd organization. This is proposed as a non-core project and Kohei Tokunaga(@ktock) will be an initial maintainer of the repository. According to the non-core document requirement, we will add the boilerplate to the project (ktock/stargz-snapshotter#23).

9 maintainer's LGTM required (2/3)

* [x]   @estesp
* [x]   @mxpv
* [x]   @AkihiroSuda
* [ ]   @crosbymichael
* [x]   @dmcgowan
* [x]   @jterry75
* [x]   @mlaventure
* [ ]   @stevvooe
* [ ]   @dchen1107
* [x]   @Random-Liu
* [x]   @mikebrow
* [ ]   @yujuhong
* [x]   @fuweid

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by mikebrow** [comment]
LGTM

**Comment by mxpv** [comment]
LGTM

**Comment by fuweid** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
FYI here are my FOSDEM slides about stargz-snapshotter: https://www.slideshare.net/AkihiroSuda/fosdem-2020-lazy-distribution-of-container-images

Benchmark results (using Docker Hub as the registry,  and an EC2 instance in Oregon region as the containerd host):
![image](https://user-images.githubusercontent.com/9248427/73910061-94dc3880-48f1-11ea-95cc-ed72617b63c1.png)
![image](https://user-images.githubusercontent.com/9248427/73910076-9d347380-48f1-11ea-86e2-cbeadebf3364.png)

Let us know if there is any remaining concern toward accepting this PR.

**Comment by jterry75** [comment]
LGTM! This is really great

**Comment by estesp** [comment]
ping @containerd/containerd-maintainers for voting and/or comments on this proposal.

**Comment by mlaventure** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by sequix** [comment]
Will you guys consider dedup here?
 eg https://github.com/ktock/container-bootfs

**Comment by ktock** [comment]
@sequix Thanks for looking into this!
 "stargz-snapshotter" (one of the "remote snapshotter" implementations. please see containerd/containerd#3731 for details of remote snapshotters.) is currently focusing on speeding up the pull operation and de-duplication is out-of-scope now.
But the concept of "remote snapshotter" itself is general and I believe we can implement another remote snapshotter which aims to de-duplication (e.g. using casync/desync).

**Comment by Random-Liu** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
Reached the quorum (9), thanks all for the voting.

@dmcgowan Could you help @ktock to transfer the repo?

**Comment by lukasheinrich** [comment]
nice to see this reach quorum: @AkihiroSuda  if you need some more real world large images to run benchmarks on you can try https://hub.docker.com/r/atlas/athena/tags (7GB compressed size)

**Comment by ktock** [comment]
Thanks a lot for the voting!

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/stargz-snapshotter
