### ISSUE TITLE
GOVERNANCE.md: replace "mailing list" with "pull requests" 

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/project#66]
We have not been using the mailing list, so we should replace "the mailing list" in GOVERNANCE.md to "pull requests".

https://github.com/containerd/project/blob/b73a06ec6945bc2788c3ce8ac3ac40d8fd4eaa8b/GOVERNANCE.md

> ## Adding maintainers
> ...
> Periodically, the existing maintainers curate a list of contributors that have shown regular activity on the project over the prior months. From this list, maintainer candidates are selected and proposed on 🔴 _the maintainers mailing list_.
>
> After a candidate has been announced on 🔴 _the maintainers mailing list_, the existing maintainers are given five business days to discuss the candidate, raise objections and cast their vote. Votes may take place on 🔴 _the mailing list_ or via pull request comment. Candidates must be approved by at least 66% of the current maintainers by adding their vote on 🔴 _the mailing list_. The reviewer role has the same process but only requires 33% of current maintainers. Only maintainers of the repository that the candidate is proposed for are allowed to vote.
> ...

> ## Removal of inactive maintainers
> ...
> If the maintainer wants to remain a maintainer, but is unable to perform the required duties they can be removed with a vote of at least 66% of the current maintainers. An 🔴 _e-mail_ is sent to 🔴 _the mailing list_, inviting maintainers of the project to vote. The voting period is five business days. Issues related to a maintainer's performance should be discussed with them among the other maintainers so that they are not surprised by a pull request removing them.

**Comment by fuweid** [comment]
LGTM

**Comment by mikebrow** [comment]
agreed.. we should either fix the instructions, or remember to send the email

**Comment by AkihiroSuda** [comment]
Fixed in #70
