### ISSUE TITLE
Add non-core project "nerdctl" to containerd organization

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/project#69]
`nerdctl` (https://github.com/AkihiroSuda/nerdctl) is a Docker-compatible CLI for containerd.

Unlike `ctr` tool, `nerdctl` has human-friendly and stable CLI based on Docker UI/UX.

`nerdctl` also supports complex operations that are not possible with `ctr`, e.g.,
- Exposing ports, using CNI portmap (and RootlessKit for rootless mode): `nerdctl run -p <PORT> ...`
- Creating restartable containers, using OCI hook: `nerdctl run --restart=always ...`
- Pulling images (`nerdctl pull`) with `~/.docker/config.json` and credential helper binaries such as `docker-credential-ecr-login`
- Showing logs of detached containers, using binary log driver: `nerdctl logs ...`
- Lazy-pulling using [stargz snapshotter](https://github.com/containerd/stargz-snapshotter)
- Decrypting [ocicrypt](https://github.com/containerd/imgcrypt) images

I'd like to propose adding `nerdctl` to @containerd organization as a non-core project.
This proposal has no impact on the scope of the core project.

10 maintainer LGTM required (2/3 of 14 maintainers)
- [x] @dims (being promoted to a maintainer in #67)
- [x] @estesp
- [x] @mxpv
- [X] @akihirosuda
- [x] @crosbymichael
- [x] @dmcgowan
- [ ] @jterry75
- [x] @mlaventure
- [x] @stevvooe
- [ ] @dchen1107
- [x] @Random-Liu
- [x] @mikebrow
- [ ] @yujuhong
- [x] @fuweid

**Comment by fuweid** [comment]
LGTM. And request to be a maintainer of nerdctl~

**Comment by AkihiroSuda** [comment]
> LGTM. And request to be a maintainer of nerdctl~

Thanks. You are a core maintainer, so you'll be a maintainer of nerdctl as well automatically, but I've sent you an invitation ahead of acceptance of this proposal 🥰

**Comment by dmcgowan** [comment]
LGTM

**Comment by Random-Liu** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by mxpv** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM :+1:

**Comment by dims** [comment]
LGTM

**Comment by samuelkarp** [comment]
LGTM (non-binding)

**Comment by stevvooe** [comment]
LGTM

**Comment by mikebrow** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
11 LGTMs, so moved the repo to https://github.com/containerd/nerdctl

Thanks all for voting.
