### ISSUE TITLE
Validate all containerd subprojects have linkage to project documents

### ISSUE THREAD

**Issue by estesp** [containerd/project#7]
Need to go project by project and either replace maintainers, governance, and contributing guidelines copies (where they exist) or simply add the boilerplate to README.md of each project with links here to `containerd/project`:

- [x] cri
- [x] containerd
- [x] go-cni
- [x] continuity
- [x] ttrpc
- [x] cgroups
- [x] go-runc
- [x] console
- [x] zfs
- [x] aufs
- [x] typeurl
- [x] fifo
- [x] btrfs
- [x] release-tool

**Comment by estesp** [comment]
typeurl: containerd/typeurl#11

**Comment by estesp** [comment]
containerd: containerd/containerd#2716

**Comment by estesp** [comment]
console: containerd/console#30

**Comment by estesp** [comment]
continuity: containerd/continuity#137

**Comment by estesp** [comment]
btrfs: containerd/btrfs#20

**Comment by estesp** [comment]
aufs: containerd/aufs#14

**Comment by estesp** [comment]
zfs: containerd/zfs#21

**Comment by estesp** [comment]
thanks to @fuweid for containerd/fifo#19 and containerd/go-runc#51

**Comment by abhi** [comment]
go-cni: https://github.com/containerd/go-cni/pull/36 thanks @fuweid

**Comment by Random-Liu** [comment]
It is a bit hard to apply this to the CRI repo.

The biggest problem is that we have some existing code that has `Kubernetes Authors` in the header, and I was told that I shouldn't remove them and just add `containerd Authors` in the same header.

**Comment by mikebrow** [comment]
from my experience you should never remove a copyright notice... but you can add additional lines...

**Comment by mikebrow** [comment]
@estesp I believe the cri project is now ready for review.

**Comment by AkihiroSuda** [comment]
Seems we can close this.
