### ISSUE TITLE
Add non-core project "rust-extensions" to containerd org

### ISSUE THREAD

**Issue by mxpv** [containerd/project#82]
There has been growing interest in Rust language ([ttrpc-rust](http://github.com/containerd/ttrpc-rust/) is a good example) and it's a de-facto language for microVMs nowadays. I've been working on crates that allow extending various parts of containerd. Potentially this can open doors for new runtime areas (especially with projects like [rust-vmm](https://github.com/rust-vmm/)) written in Rust.

I'd like to propose adding rust extensions to @containerd organization as a non-core project to push it further (will be available at `containerd/rust-extensions`)

Currently there are 4 crates:
- `containerd-client` - GRPC client to query containerd daemon APIs.
- `containerd-shim` - shim library (similar to `shim.Run` in Go) that simplifies shim development.
- `containerd-shim-logging` - shim binary logging.
- `containerd-shim-client` - TTRPC protos and shim client.

The repo with code is temporarily available [here](http://github.com/containerd/containerd-rust-extensions) for review.

This proposal has no impact on the scope of the core project.

9 maintainer's LGTM required (2/3 of 13 maintainers)
- [x] @AkihiroSuda
- [x] @crosbymichael
- [x] @dmcgowan
- [x] @estesp
- [ ] @stevvooe
- [ ] @Random-Liu
- [x] @mikebrow
- [ ] @yujuhong
- [x] @fuweid
- [x] @mxpv
- [ ] @dchen1107
- [x] @dims
- [x] @kevpar

**Comment by dmcgowan** [comment]
LGTM

**Comment by dims** [comment]
LGTM

**Comment by fuweid** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by mxpv** [comment]
ping @crosbymichael @stevvooe @Random-Liu @mikebrow @yujuhong @dchen1107 @kevpar

**Comment by mikebrow** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

Michael Crosby

**Comment by kevpar** [comment]
LGTM

**Comment by dmcgowan** [comment]
https://github.com/containerd/rust-extensions
